version: "2"
services:
  red-detector:
    build:
      context: .
      dockerfile: DockerfileARM
    restart: always
    ports:
      - 5000:5000
    devices:
      - ${VIDEO_INPUT}:/dev/video0
    environment:
      - WEB_SERVER_NAME=Video Feed
      - WEB_SERVER_HOST=0.0.0.0
      - WEB_SERVER_PORT=5000
      - MQTT_HOST=${MQTT_HOST}
